driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once

verifier:
  name: inspec

platforms:
  - name: windows-2012R2

suites:
  - name: latest
    run_list:
      - recipe[test::latest]
    attributes:
      environment_access_key: ENV['environment_access_key']
  - name: specified_version
    run_list:
      - recipe[test::specified_version]
